Milestone 1: Simple Webpage
peter-akhigbe/Hello-Microverse pull request #2
Opened 2023-01-11 17:40 UTC by peter-akhigbe

## Hello Microverse Project

In this milestone I did the following:
- created the index.hmtl file and added a single h1 that displays "Hello Microverse"
- created the styles.css file and styled the h1 using CSS
- added linter

2023-01-11 17:59 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @peter-akhigbe 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

### 🏮🏮 IMPORTANT NOTE: 

It's not good enough to close/merge PR that has been reviewed and not yet approved.  Pull Request 👉  https://github.com/peter-akhigbe/Hello-Microverse/pull/1 , next time please consider using the initial not approved PR for all re-reviews. 

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial e😊nough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 17:59 UTC, abdulhamiid commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- These sections are well customized 👍  well done.

2023-01-12 10:42 UTC, emmiiorji requested changes
Hi @peter-akhigbe, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Proper use of GitHub flow


 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 10:42 UTC, emmiiorji commented on README.md
> +This project is [MIT](./LICENSE) licensed.
As requested by the previous reviewer, it is quite important that your readme documentation is as professional as possible. I think that having a broken link on your readme is not professional enough. The link specified by highlighted code requires that you have a file called LICENSE in the root directory of your project, otherwise it'll be a broken link as shown below.

Kindly include this file. Find out how [here](https://github.com/microverseinc/readme-template/blob/e6bb90ae016bd5026a5b26a4e68d057046db7105/README.md?plain=1#L286).

![image](https://user-images.githubusercontent.com/20554583/212045657-24181ea1-65ae-4907-932d-1d770ca418f1.png)

2023-01-12 13:31 UTC, peter-akhigbe commented
I created the MIT.md file in the root of the project repository and added a link to it at the bottom of the project README

2023-01-12 13:40 UTC, roshan-bajgain approved these changes
Hi @peter-akhigbe, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 13:44 UTC, merged